// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace W3SchoolsFramework.UIMapAllPagesClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMapAllPages
    {
        
        /// <summary>
        /// ClickSearchIconToOpenSearchBox
        /// </summary>
        public void ClickSearchIconToOpenSearchBox()
        {
            #region Variable Declarations
            HtmlHyperlink uIItemHyperlink = this.UIW3SchoolsOnlineWebTuWindow.UIW3SchoolsOnlineWebTuDocument.UIItemHyperlink;
            uIItemHyperlink.DrawHighlight();
            #endregion

            // Click '' link
            Mouse.Click(uIItemHyperlink, new Point(30, 36));
        }
        
        /// <summary>
        /// EnterSearchTermInSeachBox - Use 'EnterSearchTermInSeachBoxParams' to pass parameters into this method.
        /// </summary>
        public void EnterSearchTermInSeachBox()
        {
            #region Variable Declarations
            HtmlEdit uISearchEdit = this.UIW3SchoolsOnlineWebTuWindow.UIW3SchoolsOnlineWebTuDocument.UISearchEdit;
            uISearchEdit.DrawHighlight();
            #endregion

            // Type 'HTML Tables' in 'search' text box
            uISearchEdit.Text = this.EnterSearchTermInSeachBoxParams.UISearchEditText;
        }
        
        /// <summary>
        /// ClickSearchIconToGetSearchResults
        /// </summary>
        public void ClickSearchIconToGetSearchResults()
        {
            #region Variable Declarations
            HtmlInputButton uISearchButton = this.UIW3SchoolsOnlineWebTuWindow.UIW3SchoolsOnlineWebTuDocument.UI___gcse_0Pane.UISearchButton;
            uISearchButton.DrawHighlight();
            #endregion

            // Click 'search' button
            Mouse.Click(uISearchButton, new Point(30, 15));
        }
        
        /// <summary>
        /// ClickFirstHtmlTablesLink
        /// </summary>
        public void ClickFirstHtmlTablesLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIHTMLTablesHyperlink = this.UIW3SchoolsOnlineWebTuWindow.UIW3SchoolsOnlineWebTuDocument.UI___gcse_0Pane1.UIHTMLTablesHyperlink;
            uIHTMLTablesHyperlink.DrawHighlight();
            #endregion

            // Click 'HTML Tables' link
            Mouse.Click(uIHTMLTablesHyperlink, new Point(111, 8));
        }
        
        /// <summary>
        /// VerifyThatCanadaExistsInTheFifthRowUnderCountry - Use 'VerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues' to pass parameters into this method.
        /// </summary>
        public void VerifyThatCanadaExistsInTheFifthRowUnderCountry()
        {
            #region Variable Declarations
            HtmlCell uICanadaCell = this.UIHTMLTablesInternetExWindow.UIHTMLTablesDocument.UICustomersTable.UICanadaCell;
            uICanadaCell.DrawHighlight();
            #endregion

            // Verify that the 'InnerText' property of 'Canada' cell equals 'Canada'
            Assert.AreEqual(this.VerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues.UICanadaCellInnerText, uICanadaCell.InnerText);
        }
        
        #region Properties
        public virtual EnterSearchTermInSeachBoxParams EnterSearchTermInSeachBoxParams
        {
            get
            {
                if ((this.mEnterSearchTermInSeachBoxParams == null))
                {
                    this.mEnterSearchTermInSeachBoxParams = new EnterSearchTermInSeachBoxParams();
                }
                return this.mEnterSearchTermInSeachBoxParams;
            }
        }
        
        public virtual VerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues VerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues
        {
            get
            {
                if ((this.mVerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues == null))
                {
                    this.mVerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues = new VerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues();
                }
                return this.mVerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues;
            }
        }
        
        public UIW3SchoolsOnlineWebTuWindow UIW3SchoolsOnlineWebTuWindow
        {
            get
            {
                if ((this.mUIW3SchoolsOnlineWebTuWindow == null))
                {
                    this.mUIW3SchoolsOnlineWebTuWindow = new UIW3SchoolsOnlineWebTuWindow();
                }
                return this.mUIW3SchoolsOnlineWebTuWindow;
            }
        }
        
        public UIHTMLTablesInternetExWindow UIHTMLTablesInternetExWindow
        {
            get
            {
                if ((this.mUIHTMLTablesInternetExWindow == null))
                {
                    this.mUIHTMLTablesInternetExWindow = new UIHTMLTablesInternetExWindow();
                }
                return this.mUIHTMLTablesInternetExWindow;
            }
        }
        #endregion
        
        #region Fields
        private EnterSearchTermInSeachBoxParams mEnterSearchTermInSeachBoxParams;
        
        private VerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues mVerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues;
        
        private UIW3SchoolsOnlineWebTuWindow mUIW3SchoolsOnlineWebTuWindow;
        
        private UIHTMLTablesInternetExWindow mUIHTMLTablesInternetExWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EnterSearchTermInSeachBox'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class EnterSearchTermInSeachBoxParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'HTML Tables' in 'search' text box
        /// </summary>
        public string UISearchEditText = "HTML Tables";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifyThatCanadaExistsInTheFifthRowUnderCountry'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class VerifyThatCanadaExistsInTheFifthRowUnderCountryExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Canada' cell equals 'Canada'
        /// </summary>
        public string UICanadaCellInnerText = "Canada";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIW3SchoolsOnlineWebTuWindow : BrowserWindow
    {
        
        public UIW3SchoolsOnlineWebTuWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "W3Schools Online Web Tutorials";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("W3Schools Online Web Tutorials");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIW3SchoolsOnlineWebTuDocument UIW3SchoolsOnlineWebTuDocument
        {
            get
            {
                if ((this.mUIW3SchoolsOnlineWebTuDocument == null))
                {
                    this.mUIW3SchoolsOnlineWebTuDocument = new UIW3SchoolsOnlineWebTuDocument(this);
                }
                return this.mUIW3SchoolsOnlineWebTuDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIW3SchoolsOnlineWebTuDocument mUIW3SchoolsOnlineWebTuDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIW3SchoolsOnlineWebTuDocument : HtmlDocument
    {
        
        public UIW3SchoolsOnlineWebTuDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "W3Schools Online Web Tutorials";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.w3schools.com/";
            this.WindowTitles.Add("W3Schools Online Web Tutorials");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItemHyperlink
        {
            get
            {
                if ((this.mUIItemHyperlink == null))
                {
                    this.mUIItemHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "void(0)";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Search W3Schools";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:void(0)";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "w3-hover-white w3-padding-16 w3-right";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Search W3Schools\" class=\"w3-hover";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "9";
                    this.mUIItemHyperlink.WindowTitles.Add("W3Schools Online Web Tutorials");
                    #endregion
                }
                return this.mUIItemHyperlink;
            }
        }
        
        public HtmlEdit UISearchEdit
        {
            get
            {
                if ((this.mUISearchEdit == null))
                {
                    this.mUISearchEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "gsc-i-id1";
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "search";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "search";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "gsc-input";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"search\" title=\"search\" class=\"gsc-";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUISearchEdit.WindowTitles.Add("W3Schools Online Web Tutorials");
                    #endregion
                }
                return this.mUISearchEdit;
            }
        }
        
        public UI___gcse_0Pane UI___gcse_0Pane
        {
            get
            {
                if ((this.mUI___gcse_0Pane == null))
                {
                    this.mUI___gcse_0Pane = new UI___gcse_0Pane(this);
                }
                return this.mUI___gcse_0Pane;
            }
        }
        
        public UI___gcse_0Pane1 UI___gcse_0Pane1
        {
            get
            {
                if ((this.mUI___gcse_0Pane1 == null))
                {
                    this.mUI___gcse_0Pane1 = new UI___gcse_0Pane1(this);
                }
                return this.mUI___gcse_0Pane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItemHyperlink;
        
        private HtmlEdit mUISearchEdit;
        
        private UI___gcse_0Pane mUI___gcse_0Pane;
        
        private UI___gcse_0Pane1 mUI___gcse_0Pane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UI___gcse_0Pane : HtmlDiv
    {
        
        public UI___gcse_0Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "___gcse_0";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "×\r\n\r\n\r\n \r\n\r\n\r\n\r\npowered by\r\n\r\n\r\n\r\n\r\n\r\nCu";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"___gcse_0\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "9";
            this.WindowTitles.Add("W3Schools Online Web Tutorials");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UISearchButton
        {
            get
            {
                if ((this.mUISearchButton == null))
                {
                    this.mUISearchButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = null;
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Type] = "image";
                    this.mUISearchButton.FilterProperties["Src"] = "https://www.google.com/uds/css/v2/search_box_icon.png";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = "search";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "gsc-search-button gsc-search-button-v2";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "title=\"search\" class=\"gsc-search-button ";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUISearchButton.WindowTitles.Add("W3Schools Online Web Tutorials");
                    #endregion
                }
                return this.mUISearchButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUISearchButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UI___gcse_0Pane1 : HtmlDiv
    {
        
        public UI___gcse_0Pane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "___gcse_0";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "×\r\n\r\n\r\n \r\n\r\n\r\n\r\npowered by\r\n\r\n\r\n\r\n\r\n\r\nW3";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"___gcse_0\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "9";
            this.WindowTitles.Add("W3Schools Online Web Tutorials");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHTMLTablesHyperlink
        {
            get
            {
                if ((this.mUIHTMLTablesHyperlink == null))
                {
                    this.mUIHTMLTablesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHTMLTablesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIHTMLTablesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHTMLTablesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUIHTMLTablesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "HTML Tables";
                    this.mUIHTMLTablesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/url";
                    this.mUIHTMLTablesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHTMLTablesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://www.google.com/url?q=https://www.w3schools.com/html/html_tables.asp&sa=U&" +
                        "ved=0ahUKEwiP6oD9qqnTAhWn6IMKHU_SCVUQFggEMAA&client=internal-uds-cse&usg=AFQjCNH" +
                        "xwAQw307gXdbG185FxpnfrI-mvQ";
                    this.mUIHTMLTablesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "gs-title";
                    this.mUIHTMLTablesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"gs-title\" dir=\"ltr\" href=\"https:/";
                    this.mUIHTMLTablesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIHTMLTablesHyperlink.WindowTitles.Add("W3Schools Online Web Tutorials");
                    #endregion
                }
                return this.mUIHTMLTablesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHTMLTablesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHTMLTablesInternetExWindow : BrowserWindow
    {
        
        public UIHTMLTablesInternetExWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "HTML Tables";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("HTML Tables");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHTMLTablesDocument UIHTMLTablesDocument
        {
            get
            {
                if ((this.mUIHTMLTablesDocument == null))
                {
                    this.mUIHTMLTablesDocument = new UIHTMLTablesDocument(this);
                }
                return this.mUIHTMLTablesDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHTMLTablesDocument mUIHTMLTablesDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHTMLTablesDocument : HtmlDocument
    {
        
        public UIHTMLTablesDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "HTML Tables";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/html/html_tables.asp";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.w3schools.com/html/html_tables.asp";
            this.WindowTitles.Add("HTML Tables");
            #endregion
        }
        
        #region Properties
        public UICustomersTable UICustomersTable
        {
            get
            {
                if ((this.mUICustomersTable == null))
                {
                    this.mUICustomersTable = new UICustomersTable(this);
                }
                return this.mUICustomersTable;
            }
        }
        #endregion
        
        #region Fields
        private UICustomersTable mUICustomersTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICustomersTable : HtmlTable
    {
        
        public UICustomersTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "customers";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Company\r\n\r\nContact\r\n\r\nCountry\r\n\r\nAlfreds";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=\"customers\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "7";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "6";
            this.WindowTitles.Add("HTML Tables");
            #endregion
        }
        
        #region Properties
        public HtmlCell UICanadaCell
        {
            get
            {
                if ((this.mUICanadaCell == null))
                {
                    this.mUICanadaCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUICanadaCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUICanadaCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUICanadaCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUICanadaCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Canada";
                    this.mUICanadaCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUICanadaCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "5";
                    this.mUICanadaCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUICanadaCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUICanadaCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "26";
                    this.mUICanadaCell.WindowTitles.Add("HTML Tables");
                    #endregion
                }
                return this.mUICanadaCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUICanadaCell;
        #endregion
    }
}
